# Generated by Django 5.1.4 on 2024-12-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(max_length=128, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='ФИО')),
                ('contact_info', models.TextField(max_length=128, verbose_name='Контакты')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('contact_info', models.TextField(max_length=128, verbose_name='Контакты:')),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplier_images', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='Время заказа')),
                ('order_amount', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Множитель заказа')),
                ('customer', models.ManyToManyField(to='projectForDBD.customer', verbose_name='Заказчик/покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(max_length=256, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество в наличии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Картинка')),
                ('supplier', models.ManyToManyField(to='projectForDBD.supplier', verbose_name='Поставщик')),
            ],
        ),
    ]
