# Generated by Django 5.1.4 on 2024-12-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectForDBD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'поставщик', 'verbose_name_plural': 'поставщики'},
        ),
    ]
