# Generated by Django 5.1.4 on 2024-12-17 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectForDBD', '0002_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectForDBD.product', verbose_name='Товары'),
        ),
    ]
