# Generated by Django 5.1.4 on 2024-12-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectForDBD', '0003_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, to='projectForDBD.product', verbose_name='Товары'),
        ),
    ]
